module.exports = {
  thucydides: {
    freedom: `For Thucydides, freedom is deeply tied to political power and survival. He observed how ideals of freedom can be corrupted by ambition, especially during war. In his "History of the Peloponnesian War," he shows how Athens' claim to be defending Greek freedom ultimately became a pretext for empire-building. The Athenian concept of freedom was increasingly used to justify dominance over other city-states, revealing the paradox that one state's freedom often means another's subjugation.`,

    morality: `Thucydides was not a moralist; for him, morality was secondary to interests and strategic advantage. His unflinching realism is evident in his account of the Mytilenean Debate and the Plague of Athens, where he documents how moral constraints break down under pressure. He observes that in times of crisis, "words had to change their ordinary meaning" - what was once considered immoral becomes acceptable when survival is at stake. Rather than condemning this shift, he presents it as a natural consequence of power politics and human nature.`,

    justice: `Justice depends on power, not abstract principles. In the famous Melian Dialogue, the Athenians declare: "the strong do what they can and the weak suffer what they must." This stark statement encapsulates Thucydides' view that appeals to justice are meaningless without the power to enforce them. For him, justice is not an absolute standard but varies according to the interests of those who define it. His analysis of how Sparta and Athens justified their actions shows how both sides claimed justice while pursuing advantage.`,

    power: `Power drives history. Thucydides focused on how human decisions, motivated by power, shaped events rather than attributing outcomes to divine intervention. He identified the growth of Athenian power and the fear it caused in Sparta as the "truest cause" of the Peloponnesian War, establishing a framework for understanding international relations that remains influential today. His analysis of how power shifts between states and how this creates instability anticipated modern theories of power transitions and security dilemmas.`,

    truth: `His historical method aimed to portray events as they truly happened, without myth or embellishment. Unlike his predecessor Herodotus, Thucydides rejected supernatural explanations and instead sought to uncover the true motives and causes behind events. He meticulously cross-checked eyewitness accounts, distinguished between immediate causes and underlying factors, and reconstructed speeches to reflect what "was called for in each situation." His commitment to accuracy and evidence-based analysis makes him the father of critical historiography.`,

    history: `He is considered the first critical historian, treating history as analysis of causes and consequences rather than storytelling. Thucydides believed his work would be "a possession for all time" because it revealed patterns in human behavior that would repeat throughout history. Unlike chroniclers who simply recorded events, he sought to explain why things happened, developing a sophisticated understanding of causation that distinguished between stated reasons, immediate triggers, and deeper structural causes. His methodology established history as an analytical discipline.`,

    knowledge: `Knowing the past is key to understanding the present and anticipating the future. Thucydides believed history repeats itself due to the constancy of human nature. "The sufferings which revolution brings upon cities," he wrote, "have occurred and always will occur as long as human nature remains the same." This insight into the recurrent patterns of human behavior makes his work not just a record of ancient events but a guide for understanding political crises across time. His emphasis on empirical observation and rational analysis also challenged traditional knowledge based on myth and custom.`,

    government: `He compared democracies and oligarchies, showing how both can degenerate when leaders are driven by ambition rather than the common good. In his account of the civil war in Corcyra, Thucydides demonstrates how factional conflict destroys civic unity and leads to extremism. His portrayal of Pericles offers a model of wise democratic leadership, while his depiction of Cleon warns against demagogues who manipulate public opinion. Through the contrast between Athens' democratic imperialism and Sparta's oligarchic conservatism, he explores how different governmental systems shape foreign policy and internal stability.`,

    conflict: `Conflict reveals human nature in its rawest form. The Peloponnesian War serves as Thucydides' laboratory for studying how individuals and societies behave under extreme pressure. He observes that war "is a violent teacher" that strips away civilization and reduces people to their basest instincts. His analysis of how conflict escalates through security dilemmas, alliance dynamics, and misperception provides a framework for understanding interstate conflict that remains relevant in modern international relations theory.`,

    legacy: `Thucydides' influence extends far beyond ancient history. His political realism has shaped modern international relations theory, particularly through the concept of the "Thucydides Trap" - the dangerous dynamic that occurs when a rising power threatens to displace an established one. Political scientists, military strategists, and policymakers continue to study his insights into power transitions, security dilemmas, and the causes of war. His methodological innovations established standards for critical inquiry that influence disciplines from history and political science to anthropology and sociology.`,
  },

  nietzsche: {
    freedom: `Freedom is the ability to create one's own values and live according to them. It's about overcoming traditional morality and affirming life in its entirety. In "Thus Spoke Zarathustra," Nietzsche described the "three metamorphoses of the spirit" - from camel (bearing burdens of tradition), to lion (saying "no" to imposed values), to child (saying "yes" to creation). True freedom comes when one becomes a "free spirit" who can evaluate, reject, and create values rather than inheriting them uncritically. This requires the courage to stand against convention and think "beyond good and evil."`,

    morality: `Nietzsche attacked what he called "slave morality" championed by Christianity, which glorifies weakness, pity, and equality. In "On the Genealogy of Morals," he traced how resentment of the weak against the strong inverted natural values, making powerlessness "good" and strength "evil." He proposed a "master morality" based on strength, creativity, and life-affirmation. His call to move "beyond good and evil" wasn't an endorsement of immorality, but a challenge to create higher values based on life-enhancement rather than life-denial. His concept of "amor fati" (love of fate) represents the highest affirmation - saying yes to life in its entirety.`,

    justice: `Justice is a construct of the weak to restrain the strong and protect themselves. In "Human, All Too Human," Nietzsche argued that justice originated from roughly equal power between parties making agreements. When inequality exists, the powerful have no incentive to respect justice except through prudence. He sought to transcend binary ideas like just/unjust, suggesting they reflect particular perspectives rather than absolute truths. His "perspectivism" holds that all moral judgments, including those about justice, are interpretations rather than objective facts. The truly free spirit recognizes this and creates values beyond conventional notions of justice.`,

    power: `All living beings seek to expand their power—this is the "will to power," the fundamental force of life itself. Unlike Darwin's emphasis on mere survival, Nietzsche saw organisms striving for growth, dominance, and self-overcoming. In "The Will to Power," he extended this concept beyond biology to psychology, culture, and knowledge. Even seemingly selfless acts express will to power in disguised form. For the "Übermensch" (overman), will to power manifests as self-mastery and creative transformation rather than domination of others. Nietzsche's analysis of power dynamics anticipated later thinkers like Foucault while rejecting the democratic premise that power should be equally distributed.`,

    truth: `Truth is a necessary illusion, not an objective reality we can access. In "On Truth and Lies in a Nonmoral Sense," Nietzsche described truth as "a mobile army of metaphors" and "worn-out metaphors which have become powerless." We create conceptual schemas that help us navigate reality, but mistake these for reality itself. Science, religion, and philosophy all claim to possess truth, but all are interpretations shaped by particular perspectives and drives. However, Nietzsche did not embrace relativism; he valued intellectual honesty and rigorous questioning. His "philosophy with a hammer" aimed to test established truths and shatter hollow idols.`,

    history: `History can paralyze action if overemphasized. In "On the Use and Abuse of History for Life," Nietzsche warned against excessive historicism that overwhelms the present with knowledge of the past. He prescribed a balance between remembering and forgetting, arguing that creative action requires selective forgetting. He identified three approaches to history: monumental (inspiring great deeds), antiquarian (preserving tradition), and critical (judging the past for present action). His concept of "eternal recurrence" - the thought experiment of living one's life infinitely - was a way to test whether one had truly affirmed life and transcended historical determinism.`,

    knowledge: `Knowledge is shaped by instinct, perspective, and power rather than pure reason. In "The Gay Science," Nietzsche challenged the Enlightenment faith in objective knowledge, arguing that "there are no facts, only interpretations." Our cognitive faculties evolved for survival, not truth-discovery. Every claim to knowledge reflects a particular perspective shaped by one's values, drives, and historical context. Rationality itself is not objective but driven by will. This epistemological perspectivism doesn't reject knowledge entirely but recognizes its inevitable limitations and the impossibility of achieving a "view from nowhere." True philosophers create rather than discover knowledge.`,

    government: `Nietzsche distrusted the modern State, seeing it as a tool for the herd that crushes exceptional individuals. In "Thus Spoke Zarathustra," he called the state "the coldest of all cold monsters" that speaks "lying words" about representing the people while actually serving mediocrity. Democracy, socialism, and nationalism all received his scorn as expressions of herd mentality. He had no comprehensive political theory but was consistent in opposing systems that subordinated individual greatness to collective values. His ideal was not anarchy but a culture that allowed the full development of higher types while recognizing natural hierarchy. His critique of egalitarianism and "last men" satisfied with comfort anticipates modern critiques of consumerist democracy.`,

    religion: `God is dead, and we have killed him. This famous proclamation from "The Gay Science" announces not just the decline of religious belief but the collapse of all absolute values and meaning. Christianity especially received Nietzsche's criticism as a "slave religion" that devalued earthly life in favor of an imaginary beyond. In "The Antichrist," he attacked Christianity's "war against the higher man" and its "denaturalization of values." Yet Nietzsche was not a simple atheist; he recognized religion's historical importance and admired aspects of Buddhism and pre-Christian Greek religion. His Zarathustra represents a new type of spiritual teacher who affirms this world rather than transcendence.`,

    art: `Art justifies existence aesthetically when moral and religious justifications fail. In "The Birth of Tragedy," Nietzsche analyzed Greek tragedy as a perfect balance between Apollonian form and Dionysian ecstasy. He valued art above science because it acknowledges its creative nature rather than pretending to objective truth. The true artist transforms suffering into beauty through affirmation rather than escape. Nietzsche himself wrote in an increasingly artistic style, using aphorisms, poetry, and literary devices to communicate insights that systematic philosophy couldn't capture. His concept of "life as aesthetic phenomenon" suggests that creating oneself as a work of art represents the highest form of human achievement.`,
  },

  foucault: {
    freedom: `Freedom isn't pure or absolute but is always exercised within networks of power relations. Foucault studied how institutions and discourses define the boundaries of what we experience as freedom. In "Discipline and Punish," he shows how modern "freedom" often involves internalized self-regulation rather than external coercion. His later work on "technologies of the self" explored how freedom might be practiced through conscious stylization of one's existence. For Foucault, freedom involves ongoing resistance against normalizing powers and critical awareness of how our subjectivity is shaped by historical forces. It's not a state to be achieved but a practice to be continually exercised.`,

    morality: `Morality is not universal but historically constructed and culturally enforced. In "The Use of Pleasure" and "The Care of the Self," Foucault examined how ethical systems in ancient Greece and Rome differed fundamentally from Christian and modern morality. Rather than focusing on prohibited acts or universal principles, he explored morality as self-governance shaped by social norms. His "genealogical" approach traced how moral categories like "normal," "deviant," or "perverse" emerged historically rather than reflecting natural kinds. His late work suggested ethics as an "aesthetics of existence" - a creative self-stylization rather than obedience to external codes.`,

    justice: `Justice is an instrument of power rather than its opposite. Law creates categories like "delinquent" or "normal" that control society through classification, not just prohibition. In "Discipline and Punish," Foucault traced how modern legal systems shifted from punishing bodies to reforming souls, developing more pervasive forms of control. The prison, courts, and legal psychiatry don't simply apply pre-existing justice but produce "truth" about individuals through examination and judgment. His analyses of cases like Pierre Rivière revealed how legal discourse constructs the criminal subject it claims merely to judge. For Foucault, justice systems reflect and reinforce prevailing power relations while claiming universality.`,

    power: `Power is everywhere, not just in government or law. It operates through institutions, language, and norms—it's productive, not just repressive. Unlike traditional views that see power as something possessed and exercised from above, Foucault saw it as relational, circulating through social networks. In "The History of Sexuality," he rejected the "repressive hypothesis" that power merely says "no," showing instead how power produces knowledge, pleasure, and identity. His concept of "power/knowledge" demonstrates how what counts as truth depends on who has the authority to speak. Yet power always generates resistance; where there is power, there are always counter-powers and possibilities for strategic reversal.`,

    truth: `Truth is linked to power. Whoever controls discourse defines what counts as truth in a given era. In "The Order of Things," Foucault examined how different historical periods had different "epistemes" - systems determining what could be considered knowledge. Scientific, medical, and psychiatric discourses don't simply discover pre-existing truths but constitute objects through their practices of observation, classification, and explanation. His concept of "regimes of truth" describes how societies maintain systems for distinguishing true from false statements and authorize certain people as truth-tellers. This doesn't mean truth is arbitrary, but that it's always produced within specific historical and institutional contexts.`,

    history: `Foucault rejected linear, progressive history. He developed "genealogy" to study the contingent emergence of ideas and institutions typically presented as natural or inevitable. Drawing on Nietzsche, his genealogical method exposed how concepts with apparent unity and continuity (like sexuality, madness, or criminality) are actually historical constructions with multiple, often contradictory origins. In "Madness and Civilization," he traced how the modern concept of mental illness emerged not through scientific progress but through changing social practices of exclusion. His concept of "archaeology" examined the unconscious rules governing what could be thought or said in different historical periods, revealing discontinuities where traditional history saw smooth development.`,

    knowledge: `Knowledge is not neutral or purely objective but is constructed within systems of power. Each era defines what is thinkable through unspoken rules and practices. In "The Birth of the Clinic," Foucault showed how modern medicine's "clinical gaze" wasn't simply better science but a new way of seeing that constructed the body as an object of knowledge. His analysis of the human sciences in "The Order of Things" revealed how they constitute their objects rather than discovering pre-existing human nature. For Foucault, even the knowing subject isn't given but produced through historical processes. This doesn't invalidate knowledge but requires a critical awareness of how knowledge claims are embedded in power relations.`,

    government: `Foucault analyzed how modern governments manage populations through "biopower" - the regulation of life processes including health, reproduction, and population. In lectures on "governmentality," he traced how power evolved from sovereign authority over death to administrative management of life. Modern governance operates through techniques that make individuals useful and docile by shaping their conduct rather than merely constraining it. His concept of "pastoral power" described how modern states adopted and secularized techniques from Christian pastoral care, claiming to care for both individuals and the collective. His late work on "security apparatuses" examined how liberal governance manages risk and uncertainty rather than simply imposing discipline.`,

    sexuality: `Sexuality is not a natural drive but a historical construct that became central to modern identity. In "The History of Sexuality," Foucault challenged the view that Victorian society repressed sex, arguing instead that it multiplied discourses about sex, producing sexuality as a domain of knowledge and control. Modern power doesn't suppress sexuality but incites us to speak about it, confess it, and understand ourselves through it. This "deployment of sexuality" creates subjects who believe their innermost truth lies in their sexual desires. Foucault's analysis questioned both conservative sexual morality and progressive sexual liberation narratives, suggesting both remain trapped within the same discursive formation that makes sexuality central to identity.`,

    resistance: `Where there is power, there is resistance, but resistance isn't external to power. In "The History of Sexuality," Foucault described resistance as "the odd term" in power relations - always present but distributed unevenly. Rather than imagining a grand revolution that would end domination, he focused on local "points of resistance" that continually unsettle and reconfigure power networks. His concept of "counter-conduct" describes how people develop alternative ways of being governed or governing themselves. His analysis of parrhesia (fearless speech) explored how speaking truth to power constitutes a form of ethical resistance. Though often characterized as pessimistic, his work consistently examines how freedom can be practiced within, rather than outside of, power relations.`,
  },
}
